name: Sphinx

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Make html with Sphinx
        run: |
          make html
      - name: save dist
        uses: actions/upload-artifact@v2
        if: !failure()
        with:
          name: _build
          path: ./html
